services:
  n8n:
    image: n8nio/n8n:1.102.0
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1234
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_API_ENABLE=true
      - N8N_API_AUTH_ACTIVE=true
      - N8N_API_AUTH_BASIC=false
      - N8N_API_KEY=devkey123
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  n8n-data: