version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=teamF
      - POSTGRES_PASSWORD=2025
      - POSTGRES_DB=teamFdb
    volumes:
      - .:/app
    depends_on:
      - n8n
      - postgres
    command: sh -c "npx prisma generate && npm run dev"
  n8n:
    image: n8nio/n8n:1.102.0
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1234
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_API_ENABLE=true
      - N8N_API_AUTH_ACTIVE=true
      - N8N_API_AUTH_BASIC=false
      - N8N_API_KEY=devkey123
    volumes:
      - ../n8n-data:/home/node/.n8n
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=teamF
      - POSTGRES_PASSWORD=2025
      - POSTGRES_DB=teamFdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  n8n-data:
    external: true
