global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000'] # backend 컨테이너와 연결
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # Grafana가 데이터 읽어올 수 있게 localhost x