global:
  scrape_interval: 15s
  evaluation_interval: 15s #메트릭 평가 인터벌

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000'] # backend 컨테이너와 연결
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # Grafana가 데이터 읽어올 수 있게 localhost x

  - job_name: 'express-app'
    static_configs:
      - targets: ['express:3001']